### ISSUE TITLE
[Bug]: content in main section of pdf showcase is hidden by flowchart drawer

### ISSUE THREAD

**Issue by Roshanjossey** [jina-ai/jina-ui#75]
The bug occurs in smaller screens in https://showcase.jina.ai/pdf/

The about section is hidden by flowchart drawer below.

![image](https://user-images.githubusercontent.com/8488446/135842419-c8896e73-af25-49dc-8a7f-78b5a23f714c.png)

This can be fixed by adding a margin to the bottom to allow user to scroll.

**Comment by rich5k** [comment]
Please, can this issue be assigned to me?

**Comment by garimavs** [comment]
I want to work on this issue. Would you mind assigning it to me?

**Comment by garimavs** [comment]
I have done the needed in PR-[#80]. Kindly look at it.
