### ISSUE TITLE
Trigger search on pressing enter key in input box in e-commerce showcase

### ISSUE THREAD

**Issue by Roshanjossey** [jina-ai/jina-ui#77]
You can find the showcase in https://showcase.jina.ai/e-commerce/

You can find the relevant code in https://github.com/jina-ai/jina-ui/blob/master/packages/showcases/src/pages/e-commerce.tsx#L313

**Comment by umairkarel** [comment]
```js
onChange={(event) => { if(event.key === 'Enter') setAddDesc(event.target.value) }}
```

is this what we should add [here](https://github.com/jina-ai/jina-ui/blob/master/packages/showcases/src/pages/e-commerce.tsx#L313)?

**Comment by Roshanjossey** [comment]
@umairkarel, no.

`onChange` handler is correct

I was thinking about a `onKeyUp` handler that has the same check you posted. Also, it should trigger `search` function.

**Comment by umairkarel** [comment]
```js
onKeyUp ={(event) => { 
      if(event.key === 'Enter') 
         setAddDesc(event.target.value); 
      search(addDesc) 
}}
```

Now is it correct?

**Comment by Roshanjossey** [comment]
I want you to answer that yourself.

In this case, when will `search` get called?

**Comment by umairkarel** [comment]
Sorry, I got it.

```js
onKeyUp ={(event) => { 
    if(event.key === 'Enter') {
       setAddDesc(event.target.value); 
       search(addDesc)
    }
}}
```

**Comment by Roshanjossey** [comment]
You don't have to say sorry. I just wanted to make sure that you understand what you're doing.

Remove the `setAddDesc`. it's already handled in `onChange`
Also change params of search function to `search(addDesc, ...originalDocuments)`
