### ISSUE TITLE
Change menu wording to remove the word "showcase"

### ISSUE THREAD

**Issue by Roshanjossey** [jina-ai/jina-ui#84]
![image](https://user-images.githubusercontent.com/8488446/136784219-d8957228-b96f-45b8-98d3-4952481e81a6.png)

The object that should be changed is in https://github.com/jina-ai/jina-ui/blob/master/packages/showcases/src/components/Sidebar.tsx#L22

**Comment by pedaars** [comment]
I can take a look at this
